CREATE TABLE GIOCATORE
(
    IDGIOCATORE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    VALORE DECIMAL(10,2) NOT NULL,
    GOLFATTI INT NOT NULL,
    IDSQUADRA INT NOT NULL,
    IDNAZIONE INT NOT NULL
);
  
CREATE TABLE SQUADRA
(
    IDSQUADRA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    BUDGET DECIMAL(10,2) NOT NULL,
    GOLFATTI INT NOT NULL,
    GOLSUBITI INT NOT NULL,
    VINTE INT NOT NULL,
    PERSE INT NOT NULL,
    PAREGGIATE INT NOT NULL,
    PUNTI INT NOT NULL,
    IDSTADIO INT NOT NULL,
    IDCAMPIONATO INT NOT NULL
);

CREATE TABLE STADIO
(
    IDSTADIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CAPIENZA INT NOT NULL,
    COD_PROVINCIA VARCHAR(2) NOT NULL,
    IDCITTA INT NOT NULL
);

CREATE TABLE PARTITA
(
    IDPARTITA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IDCASA INT NOT NULL,
    IDOSPITE INT NOT NULL,
    GOLCASA INT NOT NULL,
    GOLOSPITE INT NOT NULL,
    ESITO VARCHAR(100) NOT NULL,
    IDGIORNATA INT NOT NULL
);

CREATE TABLE GIORNATA
(
    IDGIORNATA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IDCAMPIONATO INT NOT NULL
);

CREATE TABLE CAMPIONATO
(
    IDCAMPIONATO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CLASSIFICA
(
    IDCLASSIFICA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IDCAMPIONATO INT NOT NULL
);

CREATE TABLE NAZIONE
(
    IDNAZIONE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CITTA
(
    IDCITTA INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    IDNAZIONE INT NOT NULL
);

ALTER TABLE GIOCATORE
ADD FOREIGN KEY (IDSQUADRA)
REFERENCES SQUADRA(IDSQUADRA);

ALTER TABLE GIOCATORE
ADD FOREIGN KEY (IDNAZIONE)
REFERENCES NAZIONE(IDNAZIONE);

ALTER TABLE SQUADRA
ADD FOREIGN KEY (IDSTADIO)
REFERENCES STADIO(IDSTADIO);

ALTER TABLE SQUADRA
ADD FOREIGN KEY (IDCAMPIONATO)
REFERENCES CAMPIONATO(IDCAMPIONATO);

ALTER TABLE STADIO
ADD FOREIGN KEY (IDCITTA)
REFERENCES CITTA(IDCITTA);

ALTER TABLE PARTITA
ADD FOREIGN KEY (IDCASA)
REFERENCES SQUADRA(IDSQUADRA);

ALTER TABLE PARTITA
ADD FOREIGN KEY (IDOSPITE)
REFERENCES SQUADRA(IDSQUADRA);

ALTER TABLE PARTITA
ADD FOREIGN KEY (IDGIORNATA)
REFERENCES GIORNATA(IDGIORNATA);

ALTER TABLE GIORNATA
ADD FOREIGN KEY (IDCAMPIONATO)
REFERENCES CAMPIONATO(IDCAMPIONATO);

ALTER TABLE CLASSIFICA
ADD FOREIGN KEY (IDCAMPIONATO)
REFERENCES CAMPIONATO(IDCAMPIONATO);

ALTER TABLE CITTA
ADD FOREIGN KEY (IDNAZIONE)
REFERENCES NAZIONE(IDNAZIONE);
